In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException

In [42]:
driver=webdriver.Chrome(r'E:\fliprobo technologies\chromedriver_win32\chromedriver.exe')
Url = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(Url)

In [43]:
Rank=[]
Name=[]
Artist=[]
Upload_date=[]
Views=[]
try:
    ranks=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[1]')
    for rank in ranks:
        Rank.append(rank.text)
except NoSuchElementException as e:
    print('Exception raised:',e)
    Rank.append('not present')

try:
    Names=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[2]')
    for name in Names:
        Name.append(name.text)
except NoSuchElementException as e:
    print('Exception raised:',e)
    Rank.append('not present')
    
try:
    Artists=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[3]')
    for artist in Artists:
        Artist.append(artist.text)
except NoSuchElementException as e:
    print('Exception raised:',e)
    Rank.append('not present')  
    
try:
    Upload_dates=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[5]')
    for Upload_dte in Upload_dates:
        Upload_date.append(Upload_dte.text)
except NoSuchElementException as e:
    print('Exception raised:',e)
    Rank.append('not present')
    
try:
    Viewss=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[4]')
    for View in Viewss:
        Views.append(View.text)
except NoSuchElementException as e:
    print('Exception raised:',e)
    Rank.append('not present')

In [44]:
print(len(Rank),len(Name),len(Artist),len(Upload_date),len(Views))

30 30 30 30 30

In [45]:
df=pd.DataFrame({'Rank':Rank,'Video':Name,'Views in billion':Views,'Artist':Artist,'Upload Date':Upload_date})
df=df.style.hide_index()
df

In [46]:
driver.close()

In [ ]:
# 2nd question answer

In [260]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException

In [261]:
driver=webdriver.Chrome('chromedriver.exe')
Url = 'https://www.bcci.tv'
driver.get(Url)
time.sleep(2)
internation_fixture=driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')
internation_fixture.click()
time.sleep(2)

Matchtitle=[]
Series=[]
Place=[]
Date=[]
Time=[]
try:
    match=driver.find_element(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
    Matchtitle.append(match.text)
except NoSuchElementException as e:
    print('Exception raised:',e)

try:
    Serie=driver.find_element(By.XPATH,'//div[@class="match-card-middle__inner d-flex justify-content-between"]')
    Series.append(Serie.text.split('\n'))
except NoSuchElementException as e:
    print('Exception raised:',e)
    
try:
    places=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/div[3]/div')
    Place.append(places.text)
except NoSuchElementException as e:
    print('Exception raised:',e)
    
try:
    tie=driver.find_element(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
    Time.append(tie.text)
except NoSuchElementException as e:
    print('Exception raised:',e)
    
try:
    date=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/div[1]/div/div[1]')
    Date.append(date.text)
except NoSuchElementException as e:
    print('Exception raised:',e)

In [262]:
print(len(Matchtitle),len(Series),len(Place),len(Date),len(Time))

1 1 1 1 1

In [263]:
df=pd.DataFrame({'Title':Matchtitle,'Series':Series,'Date':Date,'Place':Place,'Time':Time})
df

,Title,Series,Date,Place,Time
0,ICC WORLD TEST CHAMPIONSHIP FINAL 2023,"[India, vs, Australia]",7 JUN 2023,"Final - Kennington Oval, London",3:30 PM IST

In [264]:
driver.close()

In [ ]:
# 3rd question answer

In [7]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException

In [27]:
driver=webdriver.Chrome('chrome.exe')
Url = 'http://statisticstimes.com/'
driver.get(Url)
time.sleep(2)
click_on_economy=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button')
click_on_economy.click()
click_on_india=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
link=click_on_india.get_attribute('href')
driver.get(link)

In [38]:
click_on_gdpofindianstates=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
click_on_gdpofindianstates.click()
Rank=[]
State=[]
GSDP18_19=[]
GSDP19_20=[]
Share18_19=[]
GDP=[]
try:
    try:
        ranks=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[1]')
        for i in ranks:
            Rank.append(i.text)
    except NoSuchElementException as e:
        print('exception raised:',e)

    try:
        state=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[2]')
        for i in state:
             State.append(i.text)
    except NoSuchElementException as e:
        print('exception raised:',e)

    try:
        GSD18_19=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[4]')
        for i in GSD18_19:
            GSDP18_19.append(i.text)
    except NoSuchElementException as e:
        print('exception raised:',e)

    try:
        GSD19_20=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[3]')
        for i in GSD19_20:
            GSDP19_20.append(i.text)
    except NoSuchElementException as e:
        print('exception raised:',e)

    try:
        share18_19=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[5]')
        for i in share18_19:
            Share18_19.append(i.text)
    except NoSuchElementException as e:
        print('exception raised:',e)

    try:
        gdp=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[6]')
        for i in gdp:
            GDP.append(i.text)
    except NoSuchElementException as e:
        print('exception raised:',e)   

except:
    print('code is wrong unable to scrap data')

In [39]:
print(len(Rank),len(State),len(GSDP18_19),len(GSDP19_20),len(Share18_19),len(GDP))

33 33 33 33 33 33

In [41]:
df=pd.DataFrame({'Rank':Rank,'State':State,'GSDP(18-19)':GSDP18_19,'GSDP(19-20)':GSDP19_20,'Share(18-19)':Share18_19,'GDP':GDP})
df=df.style.hide_index()
df

In [42]:
driver.close()

In [ ]:
# 4th question answer

In [55]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException

In [56]:
driver=webdriver.Chrome('chrome.exe')
Url = 'https://github.com/'
driver.get(Url)
time.sleep(2)
click_on_opensource=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button')
click_on_opensource.click()
click_on_trending=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a')
click_on_trending.click()

In [60]:
url=[]
Repository=[]
description=[]
Contributors_count=[]
Language_used=[]

links=driver.find_elements(By.XPATH,'//h2[@class="h3 lh-condensed"]/a')
for i in links:
    url.append(i.get_attribute('href'))
for i in url:
    driver.get(i)
    
    try:
        repository=driver.find_element(By.XPATH,'//div[@class=" d-flex flex-wrap flex-items-center wb-break-word f3 text-normal"]') 
        Repository.append(repository.text)
    except NoSuchElementException as e:
        print('exception raised:',e)
        
    try:
        descrip=driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/main/turbo-frame/div/div/div/div[2]/div[2]/div/div[1]/div/p') 
        description.append(descrip.text)
    except NoSuchElementException as e:
        print('exception raised:',e)
        
    try:
        Contributors=driver.find_element(By.XPATH,'//div[@class="BorderGrid-row"][4]/div/h2/a/span') 
        Contributors_count.append(Contributors.text)
    except NoSuchElementException as e:
        print('exception raised:',e)
        try:
            Contributors=driver.find_element(By.XPATH,'//div[@class="BorderGrid BorderGrid--spacious"]/div[3]/div/h2/a/span') 
            Contributors_count.append(Contributors.text)
        except:
            Contributors_count.append('-')
    try:
        Language=driver.find_element(By.XPATH,'//div[@class="BorderGrid-row"][5]/div/ul') 
        Language_used.append(Language.text)
    except NoSuchElementException as e:
        print('exception raised:',e)
        try:
            Language=driver.find_element(By.XPATH,'//div[@class="BorderGrid BorderGrid--spacious"]/div[4]/div/ul') 
            Language_used.append(Language.text)
        except:
            try:
                Language=driver.find_element(By.XPATH,'//div[@class="BorderGrid BorderGrid--spacious"]/div[3]/div/ul') 
                Language_used.append(Language.text)
            except:
                Language_used.append('-')

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][4]/div/h2/a/span"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][5]/div/ul"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][4]/div/h2/a/span"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][5]/div/ul"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][4]/div/h2/a/span"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][5]/div/ul"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][4]/div/h2/a/span"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][5]/div/ul"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][4]/div/h2/a/span"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][5]/div/ul"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][4]/div/h2/a/span"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][5]/div/ul"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][5]/div/ul"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][4]/div/h2/a/span"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][4]/div/h2/a/span"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][5]/div/ul"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][4]/div/h2/a/span"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][4]/div/h2/a/span"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][5]/div/ul"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][4]/div/h2/a/span"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][5]/div/ul"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][4]/div/h2/a/span"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]
	GetHandleVerifier [0x01358E3A+2540266]
	GetHandleVerifier [0x01398959+2801161]
	GetHandleVerifier [0x0139295C+2776588]
	GetHandleVerifier [0x01182280+612144]
	(No symbol) [0x01094F6C]
	(No symbol) [0x010911D8]
	(No symbol) [0x010912BB]
	(No symbol) [0x01084857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]

exception raised: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="BorderGrid-row"][5]/div/ul"}
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x010F8893+48451]
	(No symbol) [0x0108B8A1]
	(No symbol) [0x00F95058]
	(No symbol) [0x00FC0467]
	(No symbol) [0x00FC069B]
	(No symbol) [0x00FEDD92]
	(No symbol) [0x00FDA304]
	(No symbol) [0x00FEC482]
	(No symbol) [0x00FDA0B6]
	(No symbol) [0x00FB7E08]
	(No symbol) [0x00FB8F2D]

In [58]:
print(len(Repository),len(description),len(Contributors_count),len(Language_used))

25 25 25 25

In [61]:
df=pd.DataFrame({'Repository Name':Repository,'Repository description':description,'Contributors_count':Contributors_count,'Language_used':Language_used})
df

,Repository Name,Repository description,Contributors_count,Language_used
0,facebookresearch\n/\nfairseq\nPublic,Facebook AI Research Sequence-to-Sequence Tool...,304,Python\n98.1%\nOther\n1.9%
1,JiauZhang\n/\nDragGAN\nPublic,Implementation of DragGAN: Interactive Point-b...,,Python\n100.0%
2,google\n/\ncomprehensive-rust\nPublic,This is the Rust course used by the Android te...,-,Rust\n63.1%\nAssembly\n12.4%\nHandlebars\n10.4...
3,NaiboWang\n/\nEasySpider\nPublic,A visual no-code/code-free web crawler/spider一...,4,JavaScript\n79.0%\nHTML\n13.9%\nPython\n3.4%\n...
4,w-okada\n/\nvoice-changer\nPublic,リアルタイムボイスチェンジャー Realtime Voice Changer,7,TypeScript\n46.2%\nPython\n32.0%\nJupyter Note...
5,Zeqiang-Lai\n/\nDragGAN\nPublic,"Implementation of DragGAN at ""Drag Your GAN: I...",2,Python\n83.2%\nCuda\n13.0%\nC++\n2.3%\nJupyter...
6,pengxiao-song\n/\nLaWGPT\nPublic,"🎉 Repo for LaWGPT, Chinese-Llama tuned with Ch...",,pengxiao-song Pengxiao Song\nherobrine19 cainiao
7,kyegomez\n/\ntree-of-thoughts\nPublic,Plug in and Play Implementation of Tree of Tho...,4,Python\n100.0%
8,Blazity\n/\nnext-enterprise\nPublic template,💼 An enterprise-grade Next.js boilerplate for ...,4,TypeScript\n82.2%\nJavaScript\n17.6%\nCSS\n0.2%
9,kamiyaa\n/\njoshuto\nPublic,ranger-like terminal file manager written in Rust,43,-
10,iryna-kondr\n/\nscikit-llm\nPublic,Seamlessly integrate powerful language models ...,2,Python\n100.0%
11,0nutation\n/\nSpeechGPT\nPublic,SpeechGPT: Empowering Large Language Models wi...,2,-
12,UFund-Me\n/\nQbot\nPublic,[🔥updating ...] 自动量化交易机器人 Qbot is an AI-orient...,-,Jupyter Notebook\n71.3%\nHTML\n19.4%\nPython\n...
13,casbin\n/\ncasbin\nPublic,An authorization library that supports access ...,1.6k,
14,adams549659584\n/\ngo-proxy-bingai\nPublic,⭐ 自行搭建的可先用 ModHeader 添加 X-Forwarded-For 请求头，对应...,,-
15,BlinkDL\n/\nRWKV-LM\nPublic,RWKV is an RNN with transformer-level LLM perf...,-,BlinkDL PENG Bo\nwww\nsaharNooby Alex
16,jaywalnut310\n/\nvits\nPublic,VITS: Conditional Variational Autoencoder with...,3,Python\n95.0%\nJupyter Notebook\n5.0%
17,csunny\n/\nDB-GPT\nPublic,Interact your data and environment using the l...,10,Python\n99.7%\nOther\n0.3%
18,lllyasviel\n/\nControlNet\nPublic,Let us control diffusion models!,6,Python\n100.0%
19,anse-app\n/\nanse\nPublic,"Supercharged experience for ChatGPT, DALL-E an...",8,TypeScript\n90.9%\nCSS\n4.9%\nJavaScript\n2.0%...
20,ricklamers\n/\ngpt-code-ui\nPublic,An open source implementation of OpenAI's Chat...,3,Python\n53.4%\nTypeScript\n32.0%\nCSS\n8.6%\nM...
21,Exafunction\n/\ncodeium.vim\nPublic,"Free, ultrafast Copilot alternative for Vim an...",20,Vim Script\n97.7%\nPowerShell\n2.3%
22,ysymyth\n/\ntree-of-thought-llm\nPublic,Tree of Thoughts: Deliberate Problem Solving w...,,-
23,mlc-ai\n/\nmlc-llm\nPublic,"Enable everyone to develop, optimize and deplo...",17,Python\n90.5%\nC++\n4.7%\nSwift\n2.4%\nJava\n1...
24,ymcui\n/\nChinese-LLaMA-Alpaca\nPublic,中文LLaMA&Alpaca大语言模型+本地CPU/GPU部署 (Chinese LLaMA...,-,

In [ ]:
driver.close()

In [ ]:
# 5th question answer

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException,ElementNotInteractableException

In [18]:
chrome_options=Options()
chrome_options.add_argument('--incognito')
driver=webdriver.Chrome(options=chrome_options)
Url = 'https:/www.billboard.com/'
driver.get(Url)

In [11]:
try:
    click_on_charts=driver.find_element(By.XPATH,'/html/body/div[3]/div[9]/div/div/div/ul/li[1]/h3/a')
    click_on_charts.click()
except ElementNotInteractableException as e:
    print('exception raised:',e)
    click_on_charts=driver.find_element(By.XPATH,'/html/body/div[3]/footer/div[4]/div/div/div[2]/div[3]/div/nav[3]/ul/li[1]/a')
    driver.get(click_on_charts.get_attribute('href'))

exception raised: Message: element not interactable
  (Session info: chrome=113.0.5672.127)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00228893+48451]
	(No symbol) [0x001BB8A1]
	(No symbol) [0x000C4F20]
	(No symbol) [0x000F13A6]
	(No symbol) [0x000E9AAC]
	(No symbol) [0x0010A2BC]
	(No symbol) [0x000E9586]
	(No symbol) [0x0010A614]
	(No symbol) [0x0011C482]
	(No symbol) [0x0010A0B6]
	(No symbol) [0x000E7E08]
	(No symbol) [0x000E8F2D]
	GetHandleVerifier [0x00488E3A+2540266]
	GetHandleVerifier [0x004C8959+2801161]
	GetHandleVerifier [0x004C295C+2776588]
	GetHandleVerifier [0x002B2280+612144]
	(No symbol) [0x001C4F6C]
	(No symbol) [0x001C11D8]
	(No symbol) [0x001C12BB]
	(No symbol) [0x001B4857]
	BaseThreadInitThunk [0x76697D59+25]
	RtlInitializeExceptionChain [0x77DFB74B+107]
	RtlClearBits [0x77DFB6CF+191]
	(No symbol) [0x00000000]

In [12]:
click_on_hot100=driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[3]/div/div/div[2]/div/div[1]/a/span/span')
click_on_hot100.click()

In [14]:
Songname=[]
Artistname=[]
Lastweekrank=[]
Peakrank=[]
Weeksonboard=[]
try:
    song=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li/h3')
    for i in song:
        Songname.append(i.text)
except NoSuchElementException:
    print('exception raised')
    
try:
    Artist=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[1]/span')
    for i in Artist:
        Artistname.append(i.text)
except NoSuchElementException:
    print('exception raised')
    
try:
    Lastweekra=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[4]')
    for i in Lastweekra:
        Lastweekrank.append(i.text)
except NoSuchElementException:
    print('exception raised')
    
try:
    Peakra=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[5]')
    for i in Peakra:
        Peakrank.append(i.text)
except NoSuchElementException:
    print('exception raised')
    
try:
    Weekson=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[6]')
    for i in Weekson:
        Weeksonboard.append(i.text)
except NoSuchElementException:
    print('exception raised')

In [15]:
print(len(Songname),len(Artistname),len(Lastweekrank),len(Peakrank),len(Weeksonboard))

100 100 100 100 100

In [16]:
df=pd.DataFrame({'Song name':Songname,'Artist name':Artistname,'Last week rank':Lastweekrank,'Peak rank':Peakrank,'Weeks on board':Weeksonboard})
df

,Song name,Artist name,Last week rank,Peak rank,Weeks on board
0,Last Night,Morgan Wallen,1,1,16
1,All My Life,Lil Durk Featuring J. Cole,-,2,1
2,Flowers,Miley Cyrus,3,1,18
3,Kill Bill,SZA,2,1,23
4,Ella Baila Sola,Eslabon Armado X Peso Pluma,4,4,9
...,...,...,...,...,...
95,Forever,Lil Baby Featuring Fridayy,87,8,19
96,Private Landing,Don Toliver Featuring Justin Bieber & Future,100,72,6
97,I Heard,YoungBoy Never Broke Again,-,98,1
98,Sunrise,Morgan Wallen,89,30,11
99,Happy,NF,95,54,6

In [ ]:
driver.close()

In [ ]:
# 6th question answer

In [19]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException

In [20]:
driver=webdriver.Chrome('chromedriver.exe')
Url = 'https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(Url)

In [22]:
Bookname=[]
Authorname=[]
Volumessold=[]
Publisher=[]
Genre=[]

book=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[2]')
for i in book:
    Bookname.append(i.text)
Author=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[3]')
for i in Author:
    Authorname.append(i.text)
Volumes=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[4]')
for i in Volumes:
    Volumessold.append(i.text)
Publish=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[5]')
for i in Publish:
    Publisher.append(i.text)
Gen=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[6]')
for i in Gen:
    Genre.append(i.text)

In [23]:
print(len(Bookname),len(Authorname),len(Volumessold),len(Publisher),len(Genre))

100 100 100 100 100

In [24]:
df=pd.DataFrame({'Novel':Bookname,'Author':Authorname,'Volumes sold':Volumessold,'Publisher':Publisher,'Genre':Genre})
df

,Novel,Author,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [26]:
driver.close()

In [ ]:
# 7th question answer

In [28]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException

In [29]:
driver=webdriver.Chrome('chromedriver.exe')
Url = 'https://www.imdb.com/list/ls095964455/'
driver.get(Url)

In [37]:
Name=[]
Yearspan=[]
Genre=[]
Runtime=[]
Ratings=[]
Votes=[]

try:
    name=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a')
    for i in name:
        Name.append(i.text)
except NoSuchElementException:
    print('exception raised')
    
try:
    Year=driver.find_elements(By.XPATH,'//span[@class="lister-item-year text-muted unbold"]')
    for i in Year:
        Yearspan.append(i.text)
except NoSuchElementException:
    print('exception raised')
    
try:
    Genr=driver.find_elements(By.CLASS_NAME,'genre')
    for i in Genr:
        Genre.append(i.text)
except NoSuchElementException:
    print('exception raised')
    
try:
    Run=driver.find_elements(By.CLASS_NAME,'runtime')
    for i in Run:
        Runtime.append(i.text)
except NoSuchElementException:
    print('exception raised')
    
try:
    Rating=driver.find_elements(By.XPATH,'//div[@class="ipl-rating-star small"]/span[2]')
    for i in Rating:
        Ratings.append(i.text)
except NoSuchElementException:
    print('exception raised')
    
try:
    Vote=driver.find_elements(By.XPATH,'//span[@name="nv"]')
    for i in Vote:
        Votes.append(i.text)
except NoSuchElementException:
    print('exception raised')

In [38]:
print(len(Name),len(Yearspan),len(Genre),len(Runtime),len(Ratings),len(Votes))

100 100 100 100 100 100

In [39]:
df=pd.DataFrame({'TV Shows':Name,'Year span':Yearspan,'Genre':Genre,'Run time':Runtime,'Ratings':Ratings,'Votes':Votes})
df

,TV Shows,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,162,243"
1,Stranger Things,(2016–2022),"Drama, Fantasy, Horror",51 min,8.7,"1,242,403"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,027,220"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"302,176"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"261,282"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"51,670"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"63,708"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"207,656"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7,"43,208"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"258,169"

In [40]:
driver.close()

In [ ]:
# 8th question answer

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException

In [2]:
driver=webdriver.Chrome('chromedriver.exe')
Url = 'https://archive.ics.uci.edu/'
driver.get(Url)

In [3]:
click_on_viewall_datasets=driver.find_element(By.XPATH,'//span[@class="whitetext"][2]/a')
click_on_viewall_datasets.click()

In [10]:
Datasetname=[]
Datatype=[]
Task=[]
Attributetype=[]
Noofinstances=[]
Noofattribute=[]
Year=[]
try:
    Dataset=driver.find_elements(By.XPATH,'//table[@border="1"]/tbody/tr/td[1]')
    for i in Dataset:
        Datasetname.append(i.text)
except NoSuchElementException as e:
    print('exception raised:',e)

try:
    datatype=driver.find_elements(By.XPATH,'//table[@border="1"]/tbody/tr/td[2]')
    for i in datatype:
        Datatype.append(i.text)
except NoSuchElementException as e:
    print('exception raised:',e)

try:
    task=driver.find_elements(By.XPATH,'//table[@border="1"]/tbody/tr/td[3]')
    for i in task:
        Task.append(i.text)
except NoSuchElementException as e:
    print('exception raised:',e)

try:
    attributetype=driver.find_elements(By.XPATH,'//table[@border="1"]/tbody/tr/td[4]')
    for i in attributetype:
        Attributetype.append(i.text)
except NoSuchElementException as e:
    print('exception raised:',e)

try:
    instances=driver.find_elements(By.XPATH,'//table[@border="1"]/tbody/tr/td[5]')
    for i in instances:
        Noofinstances.append(i.text)
except NoSuchElementException as e:
    print('exception raised:',e)

try:
    atribute=driver.find_elements(By.XPATH,'//table[@border="1"]/tbody/tr/td[6]')
    for i in atribute:
        Noofattribute.append(i.text)
except NoSuchElementException as e:
    print('exception raised:',e)

try:
    year=driver.find_elements(By.XPATH,'//table[@border="1"]/tbody/tr/td[7]')
    for i in year:
        Year.append(i.text)
except NoSuchElementException as e:
    print('exception raised:',e)

In [11]:
print(len(Datasetname),len(Datatype),len(Task),len(Attributetype),len(Noofinstances),len(Noofattribute),len(Year))

623 623 623 623 623 623 623

In [13]:
df=pd.DataFrame({'Data set name':Datasetname[1:],'Data type':Datatype[1:],'Task':Task[1:],'Attribute type':Attributetype[1:],'No of instances':Noofinstances[1:],'No of attribute':Noofattribute[1:],'Year':Year[1:]})
df

,Data set name,Data type,Task,Attribute type,No of instances,No of attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twit...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mo...,Univariate,Regression,Real,4000,2,2021

In [14]:
driver.close()

In [ ]:
# 9th question answer

In [15]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException

In [16]:
driver=webdriver.Chrome('chromedriver.exe')
Url = 'https://www.naukri.com/hr-recruiters-consultants'
driver.get(Url)

In [23]:
search=driver.find_element(By.XPATH,'//input[@class="sugInp"]')
search.send_keys('Data science')
click_on_search=driver.find_element(By.XPATH,'//button[@id="qsbFormBtn"]')
click_on_search.click()

In [41]:
Name=[]
Designation=[]
Company=[]
Skillstheyhirefor=[]
Location=[]
try:
    name=driver.find_elements(By.XPATH,'//span[@class="fl ellipsis"]')
    for i in name:
        Name.append(i.text)
except NoSuchElementException as e:
    print('exception raised:',e)
    
try:
    designation=driver.find_elements(By.XPATH,'//span[@class="ellipsis clr"]')
    for i in designation:
        Designation.append(i.text)
except NoSuchElementException as e:
    print('exception raised:',e)
    
try:
    company=driver.find_elements(By.XPATH,'//p[@class="highlightable"]/a[2]')
    for i in company:
        Company.append(i.text)
except NoSuchElementException as e:
    print('exception raised:',e)
    
try:
    Skills=driver.find_elements(By.XPATH,'//div[@class="hireSec highlightable"]')
    for i in Skills:
        Skillstheyhirefor.append(i.text)
except NoSuchElementException as e:
    print('exception raised:',e)
    
try:
    location=driver.find_elements(By.XPATH,'//p[@class="highlightable"]/span[2]')
    for i in location:
        Location.append(i.text)
except NoSuchElementException :
    print('exception raised:',e)    
    Location.append('-')

In [42]:
print(len(Name),len(Designation),len(Company),len(Skillstheyhirefor),len(Location))

50 50 50 50 49

In [43]:
Location.insert(30,'-')
print(len(Name),len(Designation),len(Company),len(Skillstheyhirefor),len(Location))

50 50 50 50 50

In [44]:
df=pd.DataFrame({'Name':Name,'Designation':Designation,'Company':Company,'Skills they hire for':Skillstheyhirefor,'Location':Location})
df

,Name,Designation,Company,Skills they hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
11,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
13,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
14,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
16,Vaishnavi Kudalkar,HR Executive,Codeachive learning,"Data Science, Python, Data Analytics",Mumbai
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Deeparchi Sharma,Company Recruiter,ZIGRAM,"Research, Digital Marketing, Analytics, Softwa...",Gurgaon
27,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
28,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
29,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
30,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",-
31,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
32,Dhruv Dev Dubey,Company Recruitment Head,NETAPS FOUNDATION,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
33,Avnish Mishra,Senior Technical &amp; Corporate Recruiter,RMS Risk Management Solutions,"Data Science, Machine Learning, Deep Learning,...",Noida
34,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
35,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Hyderabad / Secunderabad
36,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
37,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
38,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
39,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
40,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
41,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
42,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
43,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
44,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
45,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
46,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
47,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
48,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
49,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai

In [45]:
driver.close()